### ISSUE TITLE
Create an area talking about how to manage schema change in Astra Streaming

### ISSUE THREAD

**Issue by ddieruf** [datastax/streaming-learning-docs#10]
Warning - this is going to get involved.

**What caused this?**
Schema change is a fact of life as a developer.  Traditionally schema change is when your database model changes. One has tools like database migrations to automate/track/overcome this. Only in the world of microservices does this fit because the data model is dedicated to one service. Thus, changes are easy to consume.

What if the schema is shared? Like in a messaging system where ingest data comes from many sources and streams of processed data are made available organization-wide. There are tools to manage this but TBH you need to be a certain scale to justify the added complexity.

**Use cases**
A very good (and full of realities) example of this shared schema challenge is in change data capture (CDC). There are so many (what seem like) edge cases of how schema can change but it turns out they are not so edge case because everyone has the same problem.

Here's an excerpt from a recent thread about a customer's CDC challenges

>When I made a schema change for a flow during the development process (such as adding a column that was missing), in the first Pulsar function (which was ingesting from CDC, doing a lookup from a C* table, and returning the result), I had to update:
>- The CQL query reading from the first table
>- The Java class object the rows from the table mapped to
>- The mapping from the row's class object to CQL (though this step could be eliminated if I used the C* entity mapper)
>- The reads from Avro in Pulsar (which were not strongly typed lookups)
>- The Java class object the Pulsar record mapped to
>- The mapping between the Avro values and the Java class object used for emitting the output
>
>Then, I needed to:
>- Update the second table definition
>- Disable and re-enable CDC on the upstream table
>- Update the C* sink's mapping to the next table (which required deleting and re-creating the sink)
>- Update the second function's Avro lookups (not strongly typed)
>- Update the second function's Avro mappings to my Java class object (which fortunately was the same class that I used for the other function)
>Every time I discovered a bug in the mapping, depending on where in the flow it was, I needed to walk through all the downstream steps to fix the issue. For example, if a type was incorrect, property was misspelled, etc., each of the downstream areas had to be updated. 
>
>Debugging was also time consuming because I had to repeatedly compare code for each of the above steps, sometimes with the help of:
>- CQL queries to check table values
>- peeking topic values
>- updating function logs to provide more detailed outputs
>- inserting records into the upstream table to trigger flows

**Some deep thinking about this**

>I think there's actually an academic / industry problem here because I've seen the same underlying problem manifest across numerous technologies. (Sorry if this gets theoretical.)
>
>The problem with schema complexity between Pulsar and Cassandra is that the schema is defined separately in each of these places:
>1. Database table
>2. Pulsar topic (e.g. as Avro record)
>3. Java class
>4. Mapping between Avro (data schema) and Java
>
>CDC fuses the first two together. Pulsar functions fuse the last three together, and if the Pulsar function interacts with a database table, then it interacts with all four. Likewise, the C* sink (a Pulsar function that interacts with a database) fuses all four of them together.
When we combine CDC with a C* sink, we have a unique case where we're bridging all four areas but have both decoupling and duplication across them.
>
>The primary reason for decoupling typically is when we want freedom to vary behavior. However, one of the hallmark symptoms of tight coupling is when a change in one component forces changes in other components. That sounds like our present problem. Where this gets even more interesting is that the typical solution to tight coupling is to introduce a more functional design. So, in a stream architecture, that would lead us to think of something serverless like Pulsar functions; but clearly something is missing here, or we wouldn't be having this discussion. 

**How can documentation help**
We aren't going to solve this schema change complexity. Every use of shema-to-topic-to-function-to-topic is a different mixture of these challenges. What we can do is provide ideas and (maybe) best practices with the realities of complexity stated upfront.

Create a collection of different schema-changing scenarios and talk about how one would manage change long term. Touch points could be:
- When to use the tech to simplify things and when to manage it manually
- Could automation pipelines help track things?
- Touch on the different ways schemas change (add, update, remove) and if/why you should not do it

**Comment by cdbartholomew** [comment]
@ddieruf this is an excellent topic to focus learning docs in. In my opinion, the Pulsar docs are weak/misleading with regards to schema. To do this well, I think would require some primary research to get a good understanding of how schema actually works in Pulsar. That is, writing code that uses schema and testing the behavior. The CDC case is, of course, the most important one to document/automate, but I think some high level material about schema will help not only users of AS/Pulsar, but also those who are implementing the automation features.
