### ISSUE TITLE
How is Pulsar validated before release?

### ISSUE THREAD

**Issue by mendonk** [datastax/streaming-learning-docs#12]
Document Pulsar's testing and validation procedures.

**Comment by nicoloboschi** [comment]
## Stability
- We verify all the unit and integration tests pass (more than 8000+). 
- We deploy several fresh new kubernetes clusters for different testing purposes. This is done via [Datastax Fallout](https://github.com/datastax/fallout) and using the [Datastax Pulsar Helm chart](https://github.com/datastax/pulsar-helm-chart). We test for examples all the connectors included in the -all distribution, CDC, TLS configuration and other important scenarios. 


## Security
- We perform continuous monitoring over all the pieces included in the Luna Streaming release. Before cutting a new release, all the transitive vulnerable dependencies are patched. Checks are performed via [OWASP checker](https://owasp.org/www-project-dependency-check/) and [Sonatype](https://www.sonatype.com/products/vulnerability-scanner).
- All the docker releases are scanned via [GCR scanner](https://cloud.google.com/container-analysis/docs/automated-scanning-howto).


## Mark a release as stable
- All the releases are tagged pre-release by default. We run periodically another tests suite named ECT (enterprise certification testing), originally developed for FedEx, that verifies fault tolerance and operational stability. More info [here](https://docs.google.com/presentation/d/1omjBxvuTGTO20VEGWsYFCfG63s3RpXKGKCQqvneBPFg/edit#slide=id.g1701789215f_0_74)
- Performance are verified by using Open Messaging Benchmarks. See more info [here](https://www.youtube.com/watch?v=UTzOcdNCtzc)

**Comment by ddieruf** [comment]
Could this move to pulsar-docs?
